services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
      
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "19092:19092"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics --list --bootstrap-server localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./kafka:/etc/kafka/conf.d
      
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
      
  opcua_service:
    build: 
      context: .
      dockerfile: DockerFile
    container_name: opcua_service
    environment:
      # Central Database Configuration (External DB)
      - DB_USER=postgres
      - DB_PASSWORD=alpha
      - DB_HOST=172.27.88.85
      - DB_PORT=5432
      - DB_NAME=central_database
      
      # Plant Database Configuration (External DB)
      - PLANT_DATABASE_USER=postgres
      - PLANT_DATABASE_PASSWORD=alpha
      - PLANT_DATABASE_HOST=172.27.88.85
      - PLANT_DATABASE_PORT=5432
      - PLANT_DATABASE_NAME=plant_database
      
      # Other Services Configuration
      - KAFKA_BROKER=kafka:9092
      - OPC_UA_URL=opc.tcp://172.27.88.85:53530/OPCUA/SimulationServer
      - JOBS_SERVICE_URL=http://localhost:8002
    ports:
      - "8007:8007"
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-data:
  redis-data: